services:
  catalog-service:
    build: 
      context: ./services/catalog-service
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - devsecops-net

networks:
  devsecops-net: