services:
  catalog-service:
    image: ecommerce-devsecops-catalog-service:latest
    build: 
      context: ./services/catalog-service
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - devsecops-net

  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    networks:
      - devsecops-net

  order-service:
    build: ./services/order-service
    ports:
      - "5002:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    networks:
      - devsecops-net

networks:
  devsecops-net: